### ISSUE TITLE
前辈您好！请问有Bmob后台的配置环境说明么？

### ISSUE THREAD

**Issue by HowquaX** [tuozhaobing/TradeIn#1]
现本科在读……最近在学习基于Bmob的开发，然后在Github上看到你的这个项目，觉得完成度挺高的，想学习一番。不知道有没有具体的配置说明？

**Comment by PoseidonMRT** [comment]
麻烦参考Bmob官网，Bmob的官网网址是：http://www.bmob.cn，如果需要使用我的项目，麻烦下载Android Studio等待构建完成即可，目前这个版本的MVP设计有待优化，正在考虑重构中，在使用过程中请勿用于商业用途，谢谢。
